### ISSUE TITLE
Support for QUIC Varint

### ISSUE THREAD

**Issue by suhasHere** [Quicr/libquicr#141]
Move our implementation of encoding varint to RFC9000

this can be a decent start : https://github.com/Quicr/libquicr/blob/moq-suhas-feb2024/src/encode.cpp#L97

**Comment by TimEvens** [comment]
quic-var-int is required by the transport now as well. Transport implements now (https://github.com/Quicr/transport/blob/metrics-per-flow/include/transport/transport.h#L130), supporting both encoding and decoding for little and big endian. 

Libquicr has an implementation, but it doesn't support endlessness today, it is implemented upon encode and not in https://github.com/Quicr/libquicr/blob/main/include/quicr/uvarint.h, and it **cannot be used by the transport** due to circular submodules.

I added a lighter weight implementation https://github.com/Quicr/transport/blob/metrics-per-flow/include/transport/transport.h#L130 that supports endlessness.
